In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from matplotlib import rc
rc('text',usetex=True)
rc('font',**{'family':'serif','serif':['Computer Modern Roman']})
import matplotlib.pyplot as plt
% matplotlib inline
% config InlineBackend.figure_format = 'svg'
% config InlineBackend.rc = {'figure.figsize': (5,3.5)}

In [232]:
import numpy as np
import numpy.linalg as la
import cvxpy as cvx
from helper import solve,solved
from cd.model.utility import LinearUtility as lu, RiskNeutralUtility as rnu

In [730]:
p = 2
n = 2
# X = np.random.randint(-5,5,size=(n,p))
# X = np.random.randn(n,p)
X = np.array([[-5,-5],[3,2]])
r = np.ones(n)
# X = np.array([[-1,-1],[-2,-2],[-1,3],[-5,2]])
# r = np.array([1,1,1])
t = X*r[:,None]
# X = np.array([[1],[1],[-1]])
# r = np.array([1,-1,-5])

In [731]:
t

array([[-5., -5.],
       [ 3.,  2.]])

In [732]:
av = 2
lamb = 1/(2)
u = lu(av)
def f(q):
    return np.mean(lu(av)(np.inner(q,X*r[:,None]))) - lamb*np.linalg.norm(q)**2
qcv= solve(X,r,lamb,u=lu(av))
qcv

array([ 0.38420002, -0.57622212])

In [555]:
f(qcv),f([-1.8,0.4])

(2.6562494649815984, 2.5499999999999998)

In [170]:
msk*qcv*b

array([-0.03804182,  0.03139894])

In [171]:
msk*qcv*av*w

array([ 0.64455642, -0.06433032])

In [179]:
qcv*(b+av*w)

array([ 8.99159117,  0.99904737])

In [178]:
s5 = np.sqrt(5)
t = X*r[:,None]
neg = t*(t<0)
pos = t*(t>=0)
aneg = -np.abs(neg); apos = np.abs(pos);
sneg = np.sum(aneg,axis=0); spos = np.sum(apos,axis=0);
lneg = np.sum(1*(t<0),axis=0); lpos =  n-lneg;
msk = np.where(sneg > spos,-1,1)
l = np.where(sneg > spos,lneg,lpos)
b = np.maximum(sneg,spos)
w = np.minimum(sneg,spos)

nu = la.norm(2*w-b)
x = msk*(b+av*w)
# 1/n*np.inner(x,b-av*w) - la.norm(x)**2
x/n
# sneg,spos,b,w
# np.sum(np.abs(qcv)*av*w),np.sum(np.abs(qcv)*b)
# np.inner(x,b-av*w)
# (b-2*w)/2                           # Solution in the av=1 case
# x
# t*((msk*x)[:,None])
# t.mean(axis=0)
# np.array([-sneg,spos]).mean(axis=0)
# k = alpha*(bst/(2*wrst))
# bst,wrst,

array([-1.8,  0.2])

In [111]:
lneg,lpos

(array([14]), array([6]))

In [92]:
lneg,lpos

(array([11, 12]), array([9, 8]))

In [86]:
1*(t<0)

array([[1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [63]:
f(x)>f(qcv)

True

In [1337]:
f(qca) > f(qcv)

False

In [1428]:
t.mean(axis=0)

array([ 0.12765455, -0.0513121 , -0.15187144,  0.12622154,  0.34062048])

In [1226]:
sup+inf

0.22636498002044803

In [1433]:
t = X*r[:,None]
# neg = np.ma.masked_where(t<0,t).mean(axis=0).data
# pos = np.ma.masked_where(t>=0,t).mean(axis=0).data
neg = (t*(t<0)).mean(axis=0)
pos = (t*(t>=0)).mean(axis=0)
aneg = np.abs(neg); apos = np.abs(pos)
msk = aneg > apos
val = np.array([neg,pos])
bst = np.maximum(aneg,apos)
wrst = np.minimum(aneg,apos)
rsd = bst/(av*wrst)-1
rsd0 = bst/(av*wrst)
sup = rsd[rsd>0].sum();inf=-rsd[rsd<0].sum()
bst/(2*wrst)


array([ 0.74765738,  0.68192891,  0.78908483,  0.77472402,  1.57367396])

In [1218]:
bst,wrst

(array([ 5.17426314,  5.83144793,  6.2337369 ,  7.60393128,  8.09862684]),
 array([ 3.85248738,  4.41037797,  2.33943358,  3.91330858,  2.54698436]))

In [1146]:
t = X*r[:,None]
dir = -1*np.sign(t.mean(axis=0))
t[np.sign(t)==dir] *= av
q = t.mean(axis=0)
# q[np.sign(q)==dir] = 0
q


array([ 0.28139431, -0.16343968, -0.09617164, -0.18565251,  0.43110689])

In [1149]:
t = X*r[:,None]
t

array([[ -1.88884337e+00,   4.24031626e-01,   9.16423681e-01,
          1.55902095e+00,  -1.58600691e-01],
       [ -5.64137487e-01,   3.11497296e-01,  -4.45345980e-01,
         -2.05122403e-01,   9.00122285e-01],
       [  6.50608657e-02,  -3.17207060e-01,  -3.48298692e-01,
         -6.55449308e-03,  -2.64458972e-01],
       [  7.20864763e-01,   1.10734813e+00,  -3.68231602e-01,
         -4.16632829e-01,   1.56181806e+00],
       [  3.51495098e-02,   1.24125839e-02,   2.75181490e-03,
         -2.13800921e-02,   2.56470859e-02],
       [  2.83096928e+00,  -4.13314708e-01,   8.86614721e-01,
          6.44075885e-01,  -1.99749363e+00],
       [  2.60483105e-01,   7.22541019e-01,  -2.45518085e-01,
         -4.51541889e-01,   7.19487839e-02],
       [ -4.48036292e-01,   8.71326213e-02,   1.70258442e-01,
          5.37224214e-01,   6.34844189e-02],
       [  2.86260819e+00,   9.12171142e-01,  -1.72573790e-01,
          5.57309150e-01,   1.89033393e+00],
       [ -5.39654776e-01,   3.6682041

In [722]:
f(qcv),f(q)

(0.11726201130148481, 0.099241727958028769)

In [723]:
f(qcv)<f(q)

False

In [235]:
np.where(t>=0,t,2*t).mean()

-0.31188001046677916

In [226]:
q = np.linspace(-0.5,0.5)
plt.plot(q,f(q))

In [50]:
means = (X*r[:,None]).mean(axis=1)
mul = np.where(means>=0,1,2)
((X*r[:,None])*mul[:,None]).mean(axis=0)

array([-0.571097  , -0.28041675])

In [51]:
lu(2)(means)

array([  1.61173164e+00,  -3.42009597e-01,   1.87739248e-01,
        -9.59745553e-01,   7.54076444e-01,  -2.31739871e+00,
        -3.19847683e+00,  -3.62568392e+00,  -8.17120548e-02,
        -6.18436656e-02,  -2.22758004e-03,  -3.07097257e+00,
         1.29739431e-01,   1.59554156e+00,   5.71636316e-01,
         5.32962465e-01,  -4.58292695e-01,  -2.27430488e-01,
         3.44627924e-01,   1.02601084e-01])

In [63]:
t = X*r[:,None]
t

array([[  2.36173655e+00,   8.61726733e-01],
       [ -5.05164553e-02,  -2.91493142e-01],
       [ -2.98150564e-02,   4.05293552e-01],
       [ -6.28402947e-01,  -3.31342606e-01],
       [  1.17314093e+00,   3.35011961e-01],
       [  1.14340479e-01,  -2.43173918e+00],
       [ -2.17330687e+00,  -1.02516996e+00],
       [ -2.23108080e+00,  -1.39460311e+00],
       [  8.47375522e-02,  -1.66449607e-01],
       [ -1.45485591e-02,  -4.72951066e-02],
       [ -3.26820258e-04,  -1.90075979e-03],
       [ -2.72234164e+00,  -3.48630936e-01],
       [  7.71515798e-02,   1.82327282e-01],
       [  1.75286147e+00,   1.43822164e+00],
       [  3.03628851e-01,   8.39643781e-01],
       [  4.85603151e-01,   5.80321779e-01],
       [ -1.24094433e+00,   7.82651632e-01],
       [ -3.43592178e-01,   1.16161690e-01],
       [  3.10655418e-01,   3.78600431e-01],
       [  5.55062154e-01,  -3.49859987e-01]])

In [82]:
t2 = np.s(t>=0,t,0.5*t)
t2

array([[  2.36173655e+00,   8.61726733e-01],
       [ -2.52582276e-02,  -1.45746571e-01],
       [ -1.49075282e-02,   4.05293552e-01],
       [ -3.14201473e-01,  -1.65671303e-01],
       [  1.17314093e+00,   3.35011961e-01],
       [  1.14340479e-01,  -1.21586959e+00],
       [ -1.08665344e+00,  -5.12584978e-01],
       [ -1.11554040e+00,  -6.97301557e-01],
       [  8.47375522e-02,  -8.32248035e-02],
       [ -7.27427953e-03,  -2.36475533e-02],
       [ -1.63410129e-04,  -9.50379893e-04],
       [ -1.36117082e+00,  -1.74315468e-01],
       [  7.71515798e-02,   1.82327282e-01],
       [  1.75286147e+00,   1.43822164e+00],
       [  3.03628851e-01,   8.39643781e-01],
       [  4.85603151e-01,   5.80321779e-01],
       [ -6.20472163e-01,   7.82651632e-01],
       [ -1.71796089e-01,   1.16161690e-01],
       [  3.10655418e-01,   3.78600431e-01],
       [  5.55062154e-01,  -1.74929993e-01]])

In [86]:
np.sum(t<0,axis=0)

array([10, 10])

In [104]:
X = np.array([[1],[1],[-1]]);
r = np.array([1,1,1]);

In [103]:
solve(np.array([[1],[1],[-1]]),np.array([1,1,1]),1/2,lu(2))

7.0821676234697769e-06

In [139]:
t = (X*r[:,None])
np.where(t>=0,t,2*t).mean()

-0.50709579062664289

In [140]:
solve(X,r,1/2,lu(2))

-2.0352826803610556e-11

In [207]:
t

array([[ 1,  1],
       [-2, -1],
       [-3,  2]])

In [197]:
lu(2)(t@[-1,1]).sum()

6

In [218]:
tt = (X@X.T)@t
tt

array([[ 11,   3],
       [-25,   0],
       [-48,  21]])

In [224]:
beta = np.abs(tt.sum(axis=1))/6

In [239]:
la.solve(X@X.T,beta)

array([ -2.10167983e+16,  -1.50119988e+16,   3.00239975e+15])

In [400]:
qcv
al = solved(X,r,1/2,lu(2))
al

array([-0.00466822,  0.18704467, -0.06373011,  0.01001069,  0.03938958])

In [408]:
r = t.sum(axis=1)
r

array([  9.,  25.,   1.,  36.,  64.])

In [415]:
s = r/la.norm(r)
s


array([ 0.11524264,  0.32011844,  0.01280474,  0.46097055,  0.81950321])

In [420]:
q = la.pinv(t)@s
t*s[:,None]

array([[  6.91455831e-01,  -1.38291166e+00,   1.72863958e+00],
       [ -6.40236880e+00,   6.40236880e+00,   8.00296100e+00],
       [  0.00000000e+00,  -2.56094752e-02,   3.84142128e-02],
       [  1.10632933e+01,   0.00000000e+00,   5.53164665e+00],
       [  2.62241026e+01,  -6.55602565e+00,   3.27801283e+01]])

In [442]:
t@qcv

array([  3.37787681e+00,   2.01900482e+00,   4.27050285e-04,
        -6.79863048e-01,   5.85625716e+00])

In [488]:
d = t.sum(axis=0)/la.norm(d)
d@t.sum(axis=0)

32.326459750489221

In [507]:
d = t.sum(axis=0)
d = d/la.norm(d)
d

array([-0.83047444, -0.2460665 ,  0.06151663, -0.06151663, -0.492133  ])

In [514]:
(t*d).sum(axis=0)

array([ 22.42280988,   1.96853201,   0.12303325,   0.12303325,   7.87412802])

In [528]:
t.sum(axis=0)@(qcv/la.norm(qcv))

32.32436952616569

In [705]:
u(t*[-1,1]).mean(axis=0)


array([ 0.5, -3.5])

In [715]:
u(t*[-1,-1]).sum(axis=1)

array([ 10., -10.])

In [672]:
u(np.sum(t,axis=0))

array([-14., -18.])

In [733]:
t

array([[-5., -5.],
       [ 3.,  2.]])

In [649]:
mn

array([ 1.1, -0.7])

In [606]:
(qcv*t.mean(axis=0))

array([ 1.69969151,  1.09971695,  0.08000982])